In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [29]:
cd/content/drive/My Drive

/content/drive/My Drive


In [30]:
!unzip Training4.zip

Archive:  Training4.zip
   creating: Training4/
   creating: Training4/Training/
   creating: Training4/Training/8PSK/
  inflating: Training4/Training/8PSK/8PSK_15_01.jpeg  
  inflating: Training4/Training/8PSK/8PSK_15_02.jpeg  
  inflating: Training4/Training/8PSK/8PSK_15_03.jpeg  
  inflating: Training4/Training/8PSK/8PSK_15_04.jpeg  
  inflating: Training4/Training/8PSK/8PSK_15_05.jpeg  
  inflating: Training4/Training/8PSK/8PSK_15_06.jpeg  
  inflating: Training4/Training/8PSK/8PSK_15_07.jpeg  
  inflating: Training4/Training/8PSK/8PSK_15_08.jpeg  
  inflating: Training4/Training/8PSK/8PSK_15_09.jpeg  
  inflating: Training4/Training/8PSK/8PSK_15_10.jpeg  
  inflating: Training4/Training/8PSK/8PSK_16_01.jpeg  
  inflating: Training4/Training/8PSK/8PSK_16_02.jpeg  
  inflating: Training4/Training/8PSK/8PSK_16_03.jpeg  
  inflating: Training4/Training/8PSK/8PSK_16_04.jpeg  
  inflating: Training4/Training/8PSK/8PSK_16_05.jpeg  
  inflating: Training4/Training/8PSK/8PSK_16_06.jpeg  
 

In [31]:
!unzip Validation4.zip

Archive:  Validation4.zip
replace Validation4/Validation/BPSK/BPSK_V15_01.jpeg? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: Validation4/Validation/BPSK/BPSK_V15_01.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V15_02.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V16_01.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V16_02.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V17_01.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V17_02.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V18_01.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V18_02.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V19_01.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V19_02.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V20_01.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V20_02.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V21_01.jpeg  
  inflating: Validation4/Validation/BPSK/BPSK_V21_02.jpeg  
  inflating: Validation4/Validation/BPSK

In [0]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization

In [0]:
classes = 6
img_rows, img_cols = 200,200
batch_size= 16


In [0]:
train_dir= "/content/drive/My Drive/Training4/Training"
valid_dir = "/content/drive/My Drive/Validation4/Validation"


In [64]:
train_datagen = ImageDataGenerator(
    rescale = 1./255,
    rotation_range = 360,
    width_shift_range = 0,
    height_shift_range = 0,
    horizontal_flip = False,
    )


validation_datagen = ImageDataGenerator(rescale = 1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size = (img_rows, img_cols),
    batch_size = batch_size,
    class_mode = 'categorical',
    )



validation_generator = validation_datagen.flow_from_directory(
        valid_dir,
        target_size=(img_rows, img_cols),
        batch_size=batch_size,
        class_mode='categorical',
        shuffle=False)


Found 1560 images belonging to 6 classes.
Found 312 images belonging to 6 classes.


In [65]:
#Classification model designing part
model = Sequential()

model.add(Conv2D(128, (3, 3), padding='same',input_shape= (img_rows, img_cols, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())
model.add(Dropout(0.25))



model.add(Conv2D(256, (2, 2), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())
model.add(Dropout(0.25))

model.add(Conv2D(512, (2, 2), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())
model.add(Dropout(0.25))

model.add(Conv2D(1024, (2, 2), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())
model.add(Dropout(0.25))

model.add(Conv2D(2048, (2, 2), padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(BatchNormalization())
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(classes))
model.add(Activation('softmax'))
print(model.summary())

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_41 (Conv2D)           (None, 200, 200, 128)     3584      
_________________________________________________________________
activation_57 (Activation)   (None, 200, 200, 128)     0         
_________________________________________________________________
max_pooling2d_41 (MaxPooling (None, 100, 100, 128)     0         
_________________________________________________________________
batch_normalization_41 (Batc (None, 100, 100, 128)     512       
_________________________________________________________________
dropout_49 (Dropout)         (None, 100, 100, 128)     0         
_________________________________________________________________
conv2d_42 (Conv2D)           (None, 100, 100, 256)     131328    
_________________________________________________________________
activation_58 (Activation)   (None, 100, 100, 256)    

In [67]:
from keras.optimizers import RMSprop, SGD, Adam
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau

checkpoint = ModelCheckpoint("/content/drive/My Drive/Training4_V2.h5",
                             monitor="val_loss",
                             mode="min",
                             save_best_only = True,
                             verbose=1)



reduce_lr = ReduceLROnPlateau(monitor = 'val_loss',
                              factor = 0.001,
                              patience = 3,
                              verbose = 1,
                              min_delta = 0.0001)

callbacks = [checkpoint, reduce_lr]

model.compile(loss = 'categorical_crossentropy',
              optimizer = Adam(lr = 0.0001),
              metrics = ['accuracy'])


epochs = 5

history = model.fit_generator(
    train_generator,
    steps_per_epoch = 1560,
    epochs = epochs,
    callbacks = callbacks,
    validation_data = validation_generator,
    validation_steps = 312)

Epoch 1/5
1560/1560 [==============================] - 561s 360ms/step - loss: 0.0523 - accuracy: 0.9890 - val_loss: 0.0000e+00 - val_accuracy: 0.9871

Epoch 00001: val_loss improved from inf to 0.00000, saving model to /content/drive/My Drive/Training4_V2.h5
Epoch 2/5
1560/1560 [==============================] - 560s 359ms/step - loss: 0.0466 - accuracy: 0.9913 - val_loss: 0.0000e+00 - val_accuracy: 0.9844

Epoch 00002: val_loss did not improve from 0.00000
Epoch 3/5
1560/1560 [==============================] - 559s 359ms/step - loss: 0.0390 - accuracy: 0.9923 - val_loss: 0.0000e+00 - val_accuracy: 0.9938

Epoch 00003: val_loss did not improve from 0.00000
Epoch 4/5
1560/1560 [==============================] - 560s 359ms/step - loss: 0.0320 - accuracy: 0.9940 - val_loss: 0.0000e+00 - val_accuracy: 0.9967

Epoch 00004: val_loss did not improve from 0.00000

Epoch 00004: ReduceLROnPlateau reducing learning rate to 9.999999747378752e-08.
Epoch 5/5
1560/1560 [=============================

In [68]:
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

Y_pred = model.predict_generator(validation_generator)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
print(confusion_matrix(validation_generator.classes, y_pred))
print('Classification Report')
target_names = ['BPSK', 'QPSK', '8PSK','16QAM','32QAM','64QAM']
print(classification_report(validation_generator.classes, y_pred, target_names=target_names))

Confusion Matrix
[[52  0  0  0  0  0]
 [ 0 52  0  0  0  0]
 [ 0  0 52  0  0  0]
 [ 0  0  0 52  0  0]
 [ 0  0  0  0 52  0]
 [ 0  0  0  0  0 52]]
Classification Report
              precision    recall  f1-score   support

        BPSK       1.00      1.00      1.00        52
        QPSK       1.00      1.00      1.00        52
        8PSK       1.00      1.00      1.00        52
       16QAM       1.00      1.00      1.00        52
       32QAM       1.00      1.00      1.00        52
       64QAM       1.00      1.00      1.00        52

    accuracy                           1.00       312
   macro avg       1.00      1.00      1.00       312
weighted avg       1.00      1.00      1.00       312

